url: "https://millto.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.
logo: '/assets/img/logo.png'
logo_svg: '/assets/img/logo.svg'
icon: '/assets/img/01.png'

include:
  - _redirects
exclude:
  - config
  - plugins
  - Capfile
  - README.md

# Build settings
markdown: kramdown
permalink: /:categories/blog/:title:output_ext

# Sass
sass:
  sass_dir: _sass
  style: compressed

toc:
  min_level: 2
  max_level: 2

collections_dir: collections
collections:
  posts:
    output: false
  products:
    output: true
    permalink: /:categories/:title:output_ext
  product_categories:
    output: false

plugins:
  - jekyll-seo-tag
  - jekyll-treehouse
  - jekyll-sitemap
  - jekyll-toc

ampdir: amp

seo:
  organization:
    name: Millto
    same_as:
    logo:
      url: 'https://millto.com/assets/img/logo.png'
      width: 512
      height: 512
  website:
    name: millto.com
  person:
    name: Millto
    id: 'author/millto'

author:
  name: Millto
  image: '/assets/img/logo.png'
  logo: '/assets/img/logo.png'
  job: Millto
  bio:
  email: biuro@millto.com


defaults:
  #### languages ####
  -
    scope:
      path: ""
    values:
      lang: "en"
      full-lang: "en"

  #### US ####
  -
    scope:
      path: "en"
    values:
      lang: "en"
      full-lang: 'en'
  -
    scope:
      path: "_posts/en"
    values:
      lang: "en"
      full-lang: 'en'
      categories: "en"
  -
    scope:
      path: "_product_categories/en"
    values:
      lang: "en"
      full-lang: 'en'
      categories: "en product_categories"
  -
    scope:
      path: "_products/en"
    values:
      lang: "en"
      full-lang: "en"
      categories: "en products"

  #### PL ####
  -
    scope:
      path: "pl"
    values:
      lang: "pl"
      full-lang: "pl"
  -
    scope:
      path: "_posts/pl"
    values:
      lang: "pl"
      full-lang: "pl"
      categories: "pl"
  -
    scope:
      path: "_product_categories/pl"
    values:
      lang: "pl"
      full-lang: "pl"
      categories: "pl product_categories"
  -
    scope:
      path: "_products/pl"
    values:
      lang: "pl"
      full-lang: "pl"
      categories: "pl produkty"

  #### DE ####
  -
    scope:
      path: "de"
    values:
      lang: "de"
      full-lang: "de"
  -
    scope:
      path: "_posts/de"
    values:
      lang: "de"
      full-lang: "de"
      categories: "de"
  -
    scope:
      path: "_product_categories/de"
    values:
      lang: "de"
      full-lang: "de"
      categories: "de product_categories"
  -
    scope:
      path: "_products/de"
    values:
      lang: "de"
      full-lang: "de"
      categories: "de produkty"
