---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: _data
  label: Zarządzanie jezykami
  create: all
  match: "**/*"
  new_doc_ext: yml
- type: heading
  label: Polski (PL)
- type: directory
  path: pl
  label: Strony
  create: all
  match: "**/*"
  new_doc_ext: html
- type: directory
  path: collections/_posts/pl
  label: Posty
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - post
- type: directory
  path: collections/_products/pl
  label: Produkty
  create: all
  match: "**/*"
  new_doc_ext: html
  templates:
  - product-group
  - product
- type: directory
  path: collections/_product_categories/pl
  label: Kategorie Produktów
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - product-category
- type: heading
  label: Angielski (EN)
- type: directory
  path: en
  label: Strony
  create: all
  match: "**/*"
  new_doc_ext: html
- type: directory
  path: collections/_posts/en
  label: Posty
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - post
- type: directory
  path: collections/_products/en
  label: Produkty
  create: all
  match: "**/*"
  new_doc_ext: html
  templates:
  - product-group
  - product
- type: directory
  path: collections/_product_categories/en
  label: Kategorie Produktów
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - product-category
- type: heading
  label: Niemiecki (DE)
- type: directory
  path: de
  label: Strony
  create: all
  match: "**/*"
  new_doc_ext: html
- type: directory
  path: collections/_posts/de
  label: Posty
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - post
- type: directory
  path: collections/_products/de
  label: Produkty
  create: all
  match: "**/*"
  new_doc_ext: html
  templates:
  - product-group
  - product
- type: directory
  path: collections/_product_categories/de
  label: Kategorie Produktów
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - product-category
- type: heading
  label: Słowacki (SK)
- type: directory
  path: sk
  label: Strony
  create: all
  match: "**/*"
  new_doc_ext: html
- type: directory
  path: collections/_posts/sk
  label: Posty
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - post
- type: directory
  path: collections/_products/sk
  label: Produkty
  create: all
  match: "**/*"
  new_doc_ext: html
  templates:
  - product-group
  - product
- type: directory
  path: collections/_product_categories/sk
  label: Kategorie Produktów
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - product-category
- type: heading
  label: Czeski (CS)
- type: directory
  path: cs
  label: Strony
  create: all
  match: "**/*"
  new_doc_ext: html
- type: directory
  path: collections/_posts/cs
  label: Posty
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - post
- type: directory
  path: collections/_products/cs
  label: Produkty
  create: all
  match: "**/*"
  new_doc_ext: html
  templates:
  - product-group
  - product
- type: directory
  path: collections/_product_categories/cs
  label: Kategorie Produktów
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - product-category
- type: heading
  label: Francuski (FR)
- type: directory
  path: fr
  label: Strony
  create: all
  match: "**/*"
  new_doc_ext: html
- type: directory
  path: collections/_posts/fr
  label: Posty
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - post
- type: directory
  path: collections/_products/fr
  label: Produkty
  create: all
  match: "**/*"
  new_doc_ext: html
  templates:
  - product-group
  - product
- type: directory
  path: collections/_product_categories/fr
  label: Kategorie Produktów
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - product-category
- type: heading
  label: Hiszpański (ES)
- type: directory
  path: es
  label: Strony
  create: all
  match: "**/*"
  new_doc_ext: html
- type: directory
  path: collections/_posts/es
  label: Posty
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - post
- type: directory
  path: collections/_products/es
  label: Produkty
  create: all
  match: "**/*"
  new_doc_ext: html
  templates:
  - product-group
  - product
- type: directory
  path: collections/_product_categories/es
  label: Kategorie Produktów
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - product-category
- type: heading
  label: Włoski (IT)
- type: directory
  path: it
  label: Strony
  create: all
  match: "**/*"
  new_doc_ext: html
- type: directory
  path: collections/_posts/it
  label: Posty
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - post
- type: directory
  path: collections/_products/it
  label: Produkty
  create: all
  match: "**/*"
  new_doc_ext: html
  templates:
  - product-group
  - product
- type: directory
  path: collections/_product_categories/it
  label: Kategorie Produktów
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - product-category
- type: heading
  label: ALL
- type: jekyll-pages
  label: Strony (all)
  create: all
  new_doc_ext: html
- type: directory
  path: collections/_posts
  label: Posty (all)
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - post
- type: directory
  path: collections/_products
  label: Produkty (all)
  create: all
  match: "**/*"
  new_doc_ext: html
  templates:
  - product-group
  - product
- type: directory
  path: collections/_product_categories
  label: Kategorie Produktów (all)
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - product-category
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
