---
label: Product Category
hide_body: true
fields:
- name: name
  type: text
  config:
    required: true
  label: Nazwa
  description: Nazwa kategorii
- name: title
  type: text
  config:
    required: false
  label: Nazwa
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
  label: Opis
  description: Krótki opis kategorii
pages:
- collections/_product_categories/sk/stavebne-vyrobky.md
- collections/_product_categories/sk/technologia-vykurovania.md
- collections/_product_categories/sk/vodne-instalacie.md
