---
label: Product Group
hide_body: true
fields:
- name: base
  type: include
  config: {}
  template: product-base
  label: Podstawowe
- name: layout
  type: text
  config:
    required: true
  label: Layout
  default: product-group
pages:
- collections/_products/pl/rozdzielacze-co.md
