---
label: Product
hide_body: false
fields:
- name: layout
  type: text
  config:
    required: true
  label: Layout
  default: product
- name: parent_product_path
  type: select
  default: []
  config:
    required: false
    options: []
    source:
      type: pages
      section: produkty-c160222d-3565-4bb2-82c3-907bc7a2ad9b
      file: 
      path: 
  label: Produkt nadrzędny
  description: Jeśli będzie uzupełniony, produkt pojawi przy produkcie grupowym
- name: base
  type: include
  config: {}
  template: product-base
  label: Podstawowe
- name: card_intro
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
  label: Skrót na karcie produktu
- name: seo_content
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
  label: Seo Content
  description: Doatkowy content pod seo
pages:
- collections/_products/cs/nivelacni-system-na-dlazbu.html
- collections/_products/cs/nivelacni-system-na-dlazbu.html
- collections/_products/cs/revizni-sachta.html
- collections/_products/cs/revizni-sachta.html
- collections/_products/de/fliesen-nivelliersystem.html
- collections/_products/de/fliesen-nivelliersystem.html
- collections/_products/de/kontrollschacht.html
- collections/_products/de/kontrollschacht.html
- collections/_products/de/thermischer-stellantrieb.html
- collections/_products/de/thermostatventil.html
- collections/_products/de/thermostatventil.html
- collections/_products/en/manhole.html
- collections/_products/en/manhole.html
- collections/_products/en/thermal-actuator.html
- collections/_products/en/thermostatic-valve.html
- collections/_products/en/thermostatic-valve.html
- collections/_products/en/tile-leveling-system.html
- collections/_products/en/tile-leveling-system.html
- collections/_products/es/pozo-de-visita.html
- collections/_products/es/pozo-de-visita.html
- collections/_products/es/sistema-de-nivelacion-de-azulejos.html
- collections/_products/es/sistema-de-nivelacion-de-azulejos.html
- collections/_products/es/valvula-termostatica.html
- collections/_products/es/valvula-termostatica.html
- collections/_products/fr/actionneur-thermique.html
- collections/_products/fr/regard-de-visite.html
- collections/_products/fr/regard-de-visite.html
- collections/_products/fr/systeme-de-nivellement-des-tuiles.html
- collections/_products/fr/systeme-de-nivellement-des-tuiles.html
- collections/_products/fr/vanne-thermostatique.html
- collections/_products/fr/vanne-thermostatique.html
- collections/_products/it/pozzetto-di-ispezione.html
- collections/_products/it/pozzetto-di-ispezione.html
- collections/_products/it/sistema-di-livellamento-delle-piastrelle.html
- collections/_products/it/sistema-di-livellamento-delle-piastrelle.html
- collections/_products/it/valvola-termostatica.html
- collections/_products/it/valvola-termostatica.html
- collections/_products/pl/glowica-termostatyczna.html
- collections/_products/pl/glowica-termostatyczna.html
- collections/_products/pl/kominek-wentylacyjny.html
- collections/_products/pl/kominek-wentylacyjny.html
- collections/_products/pl/osadnik-rynnowy.html
- collections/_products/pl/osadnik-rynnowy.html
- collections/_products/pl/pokrywa-studzienki.html
- collections/_products/pl/pokrywa-studzienki.html
- collections/_products/pl/rotametr.html
- collections/_products/pl/rotametr.html
- collections/_products/pl/rozdzielacze-co/do-grzejnikow.html
- collections/_products/pl/rozdzielacze-co/do-grzejnikow.html
- collections/_products/pl/rozdzielacze-co/do-podlogowki.html
- collections/_products/pl/rozdzielacze-co/do-podlogowki.html
- collections/_products/pl/silownik-termoelektryczny.html
- collections/_products/pl/silownik-termoelektryczny.html
- collections/_products/pl/studzienka-rewizyjna.html
- collections/_products/pl/studzienka-rewizyjna.html
- collections/_products/pl/system-poziomowania-plytek.html
- collections/_products/pl/system-poziomowania-plytek.html
- collections/_products/pl/zawor-termostatyczny.html
- collections/_products/pl/zawor-termostatyczny.html
- collections/_products/sk/nivelacny-system-na-dlazbu.html
- collections/_products/sk/nivelacny-system-na-dlazbu.html
- collections/_products/sk/revizna-sachta.html
- collections/_products/sk/revizna-sachta.html
- collections/_products/sk/termostaticky-ventil.html
- collections/_products/sk/termostaticky-ventil.html
