---
label: Product Group
hide_body: false
fields:
- name: layout
  type: text
  config:
    required: true
  label: Layout
  default: product-group
- name: base
  type: include
  config: {}
  template: product-base
  label: Podstawowe
pages:
- collections/_products/de/heizkreisverteiler.html
- collections/_products/en/radiant-heat-manifold.html
- collections/_products/es/colector-para-calefaccion.html
- collections/_products/fr/collecteur.html
- collections/_products/it/collettore-di-calore-radiante.html
- collections/_products/sk/rozdelovac.html
