---
label: Product Group
hide_body: false
fields:
- name: layout
  type: text
  config:
    required: true
  label: Layout
  default: product-group
- name: base
  type: include
  config: {}
  template: product-base
  label: Podstawowe
pages:
- collections/_products/de/planning-a-heating-system-in-a-building-choose-the-right-manifold.find-the-best-equipment-and-take-care-of-your-thermal-comfort.html
- collections/_products/en/radiant-heat-manifold.html
