---
label: Product [base]
hide_body: true
fields:
- type: text
  name: name
  label: Nazwa
  config:
    required: true
- type: textarea
  name: description
  label: Opis
  config:
    wysiwyg: true
    schema:
      format: markdown
- name: category
  type: select
  default: []
  config:
    required: false
    options: []
    source:
      type: pages
      section: kategorie-produktow
      file: 
      path: 
  label: Kategoria
  description: Jeśli będzie uzupełniona, produkt pojawi się przy kategorii
