---
label: Product Group
hide_body: true
fields:
- name: layout
  type: text
  config:
    required: true
  label: Layout
  default: product-group
- name: base
  type: include
  config: {}
  template: product-base
  label: Podstawowe
