---
label: Product
hide_body: true
fields:
- name: layout
  type: text
  config:
    required: true
  label: Layout
  default: product
- name: parent_product_path
  type: select
  default: []
  config:
    required: false
    options: []
    source:
      type: pages
      section: produkty
      file: 
      path: 
  label: Produkt nadrzędny
  description: Jeśli będzie uzupełniony, produkt pojawi przy produkcie grupowym
- name: base
  type: include
  config: {}
  template: product-base
  label: Podstawowe
