---
label: Product
hide_body: true
fields:
- name: layout
  type: text
  config:
    required: true
  label: Layout
  default: product
- name: name
  type: text
  config:
    required: true
  label: Nazwa
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
  label: Opis
