---
label: Product
hide_body: false
fields:
- name: layout
  type: text
  config:
    required: true
  label: Layout
  default: product
- name: parent_product_path
  type: select
  default: []
  config:
    required: false
    options: []
    source:
      type: pages
      section: produkty
      file: 
      path: 
  label: Produkt nadrzędny
  description: Jeśli będzie uzupełniony, produkt pojawi przy produkcie grupowym
- name: base
  type: include
  config: {}
  template: product-base
  label: Podstawowe
- name: card_intro
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
  label: Skrót na karcie produktu
- name: seo_content
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
  label: Seo Content
  description: Doatkowy content pod seo
pages:
- collections/_products/pl/glowica-termostatyczna-1.html
- collections/_products/pl/rozdzielacze-co/rozdzielacz-co-mosiezny-nieuzbrojony.html
