---
label: Product [base]
hide_body: true
fields:
- name: category_path
  type: select
  default: []
  config:
    required: false
    options: []
    source:
      type: pages
      section: test
      file: 
      path: 
  label: Kategoria
  description: Jeśli będzie uzupełniona, produkt pojawi się przy kategorii
- type: text
  name: name
  label: Nazwa
  config:
    required: true
- name: title
  type: text
  config:
    required: false
  label: SEO Tytuł
- type: textarea
  name: description
  label: SEO Opis
  config:
    wysiwyg: true
    schema:
      format: markdown
- name: intro
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Intro
- name: date
  type: datetime
  label: Data publikacji
  description: ''
  config:
    required: true
    date_format: 
    time_format: 
    display_utc: false
  default: now
- name: update_date
  type: datetime
  label: Data aktualizacji
  description: ''
  config:
    required: true
    date_format: 
    time_format: 
    display_utc: false
  default: now
- name: photo
  type: file
  config:
    maxSize: 64
  label: Zdjęcie
