---
label: Product [base]
hide_body: true
fields:
- type: text
  name: layout
  label: layout
- type: text
  name: name
  label: name
- type: textarea
  name: description
  label: description
- type: text
  name: category
  label: category
