---
label: Product
hide_body: false
fields:
- name: layout
  type: text
  config:
    required: true
  label: Layout
  default: product
- name: parent_product_path
  type: select
  default: []
  config:
    required: false
    options: []
    source:
      type: pages
      section: produkty-c160222d-3565-4bb2-82c3-907bc7a2ad9b
      file: 
      path: 
  label: Produkt nadrzędny
  description: Jeśli będzie uzupełniony, produkt pojawi przy produkcie grupowym
- name: base
  type: include
  config: {}
  template: product-base
  label: Podstawowe
- name: card_intro
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
  label: Skrót na karcie produktu
- name: seo_content
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
  label: Seo Content
  description: Doatkowy content pod seo
pages:
- collections/_products/cs/termostaticky-ventil.html
- collections/_products/de/thermostatventil.html
- collections/_products/de/thermostatventil.html
- collections/_products/en/thermostatic-valve.html
- collections/_products/en/thermostatic-valve.html
- collections/_products/pl/glowica-termostatyczna.html
- collections/_products/pl/glowica-termostatyczna.html
- collections/_products/pl/kominek-wentylacyjny.html
- collections/_products/pl/kominek-wentylacyjny.html
- collections/_products/pl/osadnik-rynnowy.html
- collections/_products/pl/osadnik-rynnowy.html
- collections/_products/pl/pokrywa-studzienki.html
- collections/_products/pl/pokrywa-studzienki.html
- collections/_products/pl/rotametr.html
- collections/_products/pl/rotametr.html
- collections/_products/pl/rozdzielacze-co/do-grzejnikow.html
- collections/_products/pl/rozdzielacze-co/do-grzejnikow.html
- collections/_products/pl/rozdzielacze-co/do-podlogowki.html
- collections/_products/pl/rozdzielacze-co/do-podlogowki.html
- collections/_products/pl/silownik-termoelektryczny.html
- collections/_products/pl/silownik-termoelektryczny.html
- collections/_products/pl/studzienka-rewizyjna.html
- collections/_products/pl/studzienka-rewizyjna.html
- collections/_products/pl/system-poziomowania-plytek.html
- collections/_products/pl/system-poziomowania-plytek.html
- collections/_products/pl/zawor-termostatyczny.html
- collections/_products/pl/zawor-termostatyczny.html
