---
label: Product
hide_body: true
fields:
- name: layout
  type: text
  config:
    required: true
  label: Layout
  default: product
- name: base
  type: include
  config: {}
  template: product-base
  label: Podstawowe
pages:
- collections/_products/pl/rozdzielacze-co/rozdzielacz-co-mosiezny-nieuzbrojony.md
