---
label: Product
hide_body: true
fields:
- name: layout
  type: text
  config:
    required: true
  label: Layout
  default: product
- name: base
  type: include
  config: {}
  template: product-base
  label: Podstawowe
- name: parent_product_path
  type: select
  default: []
  config:
    required: false
    options: []
    source:
      type: pages
      section: produkty
      file:
      path:
  label: Produkt nadrzędny
  description: Jeśli będzie uzupełniony, produkt pojawi przy produkcie grupowym  
pages:
- collections/_products/pl/rozdzielacze-co/rozdzielacz-co-mosiezny-nieuzbrojony.md
