---
label: Product Group
hide_body: false
fields:
- name: layout
  type: text
  config:
    required: true
  label: Layout
  default: product-group
- name: base
  type: include
  config: {}
  template: product-base
  label: Podstawowe
pages:
- collections/_products/en/radiant-heat-manifold.html
